// client/src/components/user-list/UserList.tsx
import React, { Component } from 'react'
import { User } from '../types/types'
import "./UserList.css"

export type Props = {
  users?: User[],
}

export class UserList extends Component<Props> {
  render() {
    const { users } = this.props
    const usersItems = users && users.map(user => {
      return (
        <li className="list-group-item">
          <span>{user.name}</span>
        </li>
      )
    })
    return (
      <div className="container">
        <h2>Lista de usuarios</h2>
        <ul className="list-group user-list">
          {usersItems}
        </ul>
      </div>
    )
  }
}

export default UserList

// client/src/app/components/user-list/user-list.component.ts
import { Component, OnInit } from '@angular/core';
import {UserService} from '../../services/user.service';
import {User} from '../../models/User';

@Component({
  selector: 'app-user-list',
  templateUrl: './user-list.component.html',
  styleUrls: ['./user-list.component.css']
})
export class UserListComponent implements OnInit {

  users: User[] = [];

  constructor(private userService: UserService) { }

  ngOnInit(): void {
    this.userService.getAll().subscribe(
      users => {
        this.users = users;
      },
      error => {
        console.log('Error when fetching users');
      }
    );
  }

}

<div class="container">
  <h2>Lista de usuarios</h2>
  <ul class="list-group user-list">
    <li class="list-group-item" *ngFor="let user of users">
      <span>{{user.name}}</span>
    </li>
  </ul>
</div>
